### ISSUE TITLE
Project Charter Review

### ISSUE THREAD

**Issue by ChengHaoKe** [MSIA/2021-msia423-rice-brian-project#1]
What's good:
1. Cool project name
2. Informative and complete information on the data source 
3. Well thought out model performance metric and mission
4. Data set's size is small but contains a large number of variables
5. Background information explains the vision's importancce

Suggestions:
1. The plan for A/B testing between musicians should indicate that it will be randomized. This is unclear in the project charter
2. Past project charter examples have both words capitalized. The word `charter` is not capitalized in the readme file.

**Comment by brianrice2** [comment]
Thanks CH, appreciate your help 😄
